// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEN1hG68P-vIYipDh4efcn_CgxJVyiWjs',
    appId: '1:539260738665:android:7132ceeae96b50172a16f8',
    messagingSenderId: '539260738665',
    projectId: 'qazstep-777',
    storageBucket: 'qazstep-777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03MqWrwbs7qeTfH2cOIpJ4Ct_lGuwaQw',
    appId: '1:539260738665:ios:c82bdd0cb5012ffd2a16f8',
    messagingSenderId: '539260738665',
    projectId: 'qazstep-777',
    storageBucket: 'qazstep-777.firebasestorage.app',
    androidClientId: '539260738665-g5inqotodtp4q9d7gom1n3s5si3f031n.apps.googleusercontent.com',
    iosClientId: '539260738665-635uq0ekflhse7ivae88is7gkqpfscla.apps.googleusercontent.com',
    iosBundleId: 'com.krmeiirbek.qazstep',
  );

}